apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      serviceAccountName: job-service-account
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets"
      containers:
      - name: s3-to-smb
        image: registry.hub.docker.com/ubuntu-cifs-awscli:latest
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "hello"
      restartPolicy: Never
